scrape_configs:
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
    - role: pod
  - job_name: 'kafka'
    static_configs:
    - targets: ['kafka-service:9092']
  - job_name: 'redis'
    static_configs:
    - targets: ['redis-service:6379']
