- hosts: all
  become: yes
  tasks:
    - name: Update and upgrade APT packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Kubernetes tools
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - kubectl
        - kubeadm
        - kubelet

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started
